# Generated by Django 3.1.5 on 2021-02-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='carimg',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg1',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg2',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg3',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg4',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media'),
        ),
    ]
