# Generated by Django 3.1.5 on 2021-02-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0003_auto_20210201_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rsvdateramassage',
            field=models.DateTimeField(verbose_name='Date de Prise Voiture'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rsvdateretour',
            field=models.DateTimeField(verbose_name='Date de Retour Voiture'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rsvlieuramassage',
            field=models.CharField(max_length=150, verbose_name='Lieux de Prise Voiture'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rsvlieuretour',
            field=models.CharField(max_length=150, verbose_name='Lieux de Retour Voiture'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rsvmailreservant',
            field=models.EmailField(max_length=150, verbose_name='Email du Reservant Voiture'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rsvnomreservant',
            field=models.CharField(max_length=150, verbose_name='Nom du Reservant Voiture'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rsvphonereservant',
            field=models.IntegerField(verbose_name='Telephone du Reservant Voiture'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rsvprennomreservant',
            field=models.CharField(max_length=150, verbose_name='Prenom du Reservant Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carcarburant',
            field=models.CharField(max_length=50, verbose_name='Carburant Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carcategorie',
            field=models.CharField(max_length=50, verbose_name='Categorie Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image Principale Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg1',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image1 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg2',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image2 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg3',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image3 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg4',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image4 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carmoteur',
            field=models.CharField(max_length=50, verbose_name='Moteur Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carnom',
            field=models.CharField(max_length=50, verbose_name='Nom Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carpassager',
            field=models.IntegerField(verbose_name='Passager'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carporte',
            field=models.IntegerField(verbose_name='Nbre Porte'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carsprix',
            field=models.IntegerField(verbose_name='Prix Voiture'),
        ),
    ]
