# Generated by Django 3.1.5 on 2021-02-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0005_auto_20210201_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='carimg',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image Principale Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg1',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image1 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg2',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image2 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg3',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image3 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg4',
            field=models.ImageField(upload_to='E:\\CarsLocation\\Dr_Digit_projet\\media', verbose_name='Image4 Voiture'),
        ),
    ]
