# Generated by Django 3.1.5 on 2021-02-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycarapp', '0006_auto_20210202_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='carimg',
            field=models.ImageField(upload_to='image/', verbose_name='Image Principale Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg1',
            field=models.ImageField(upload_to='image/', verbose_name='Image1 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg2',
            field=models.ImageField(upload_to='image/', verbose_name='Image2 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg3',
            field=models.ImageField(upload_to='image/', verbose_name='Image3 Voiture'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carimg4',
            field=models.ImageField(upload_to='image/', verbose_name='Image4 Voiture'),
        ),
    ]
